Improve error message when tests can't find image
It momentarily confused me why the tests wouldn't work locally. I've removed
the `should be available` test because this doesn't report the correct thing
when `@image` is `nil`. Because of this we no longer need `@image`, we just
want the ID.

Before:

    1) bosh-init image should be available
       Failure/Error: set :docker_image, @image.id
       NoMethodError:
         undefined method `id' for nil:NilClass

       # ./spec/bosh-init/bosh-init_spec.rb:8:in `block (2 levels) in <top (required)>'

After:

    1) bosh-init image installs the right version of Ubuntu
       Failure/Error: raise "Docker image '#{name}' not found. You may need to run 'rake build:<name>' first" unless image
       RuntimeError:
         Docker image 'bosh-init:latest' not found. You may need to run 'rake build:<name>' first

       # ./spec/spec_helper.rb:20:in `find_image_id'
       # ./spec/bosh-init/bosh-init_spec.rb:7:in `block (2 levels) in <top (required)>'